### ISSUE TITLE
Can not run tests on QUnit 0.18.0

### ISSUE THREAD

**Issue by patkoscsaba** [karma-runner/karma-qunit#26]
When I try to run tests using QUnit _and_ require.js, I get this error:
![image](https://cloud.githubusercontent.com/assets/1277513/7132223/f6497b5a-e28f-11e4-8a75-3ac342768905.png)
I reported this first for QUnit. They directed me here. Check here for more details & an example project that fails: https://github.com/jquery/qunit/issues/807#issuecomment-92397437

**Comment by ldez** [comment]
Your problem not concern `karma-qunit`.

Your log is very clear : `Mismatched anonymous define() module`.
In your log, you can see link http://requirejs.org/docs/errors.html#mismatch, go to this link for more informations.

You can read also : http://karma-runner.github.io/0.12/plus/requirejs.html

I corrected your project and I can run the tests.

Reads the log and search a little more before opening issue, otherwise ask your question on StackOverflow before.

**Please close this issue.**

**Comment by ldez** [comment]
Sorry.
The probleme is in QUnit:
line 1959:
```javascript
if ( typeof define === "function" && define.amd ) {
	define( function() {
		return QUnit;
	} );
	QUnit.config.autostart = false;
}
```

**Comment by ldez** [comment]
In `karma.conf.js` replace `frameworks: [ 'qunit', 'requirejs'],` by `frameworks: [ 'requirejs', 'qunit'],`

**Comment by ldez** [comment]
The problem can be dirty solve like that: in `karma.conf.js` replace `frameworks: [ 'qunit', 'requirejs'],` by `frameworks: [ 'requirejs', 'qunit'],`

**Comment by ldez** [comment]
And for your code, change also:
```javascript
    // list of files / patterns to load in the browser
    files: [
      'test-main.js',
      {pattern: 'src/**/*.js', included: false},
      {pattern: 'test/**/*.js', included: false}
    ],
```

and `exampleTest.js`:
```javascript
define(['src/exampleSource'],function () {

	QUnit.test('QUnit 0.18.0 works', function (assert) {
		QUnit.assert.ok(actualCode() == true);
	});
});
```

**Comment by Krinkle** [comment]
@dignifiedquire Looks like this was an issue with user config loading `requirejs` and `qunit` in a different order. I think this can be closed now.
